spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: meharet.salmanov@gmail.com
#    app password
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true